name: PlatformIO Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Put secrets in place
        run: |
          cat << EOF > ./config/secrets.ini
          ${{ secrets.CONFIG_SECRETS_INI }}
          EOF
          mkdir ./ssl
          cat << EOF > ./ssl/private.key
          ${{ secrets.SSL_SIGNATURE_PRIVATE_KEY }}
          EOF

      - name: Build PlatformIO Project
        run: pio run
